In [ ]:
import pandas as pd

In [ ]:
#Task 1: Read a CSV file into a DataFrame
#File: 'sample_data.csv' (create your own with some dummy data if needed)
#Task 2: Save the DataFrame into a new Excel file named 'output_data.xlsx'
#Task 3: Load a JSON file named 'sample_data.json' into a DataFrame
#Task 4: Convert a DataFrame into a JSON file named 'export_data.json'

In [ ]:
df = pd.read_csv('')

In [ ]:
import pandas as pd
import numpy as np

# Generate a sample sales dataset
data = {
    'OrderID': np.arange(101, 111),
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam', 'Headphones', 'Speaker', 'Router', 'Printer', 'SSD'],
    'Quantity': np.random.randint(1, 5, size=10),
    'UnitPrice': np.round(np.random.uniform(20, 1500, size=10), 2),
    'OrderDate': pd.to_datetime(pd.date_range(start='2023-01-01', periods=10, freq='D')),
    'Region': np.random.choice(['North', 'South', 'East', 'West'], size=10)
}

sales_df = pd.DataFrame(data)
sales_df['TotalPrice'] = sales_df['Quantity'] * sales_df['UnitPrice']

print("Sample Sales Dataset:")
print(sales_df.head())

Sample Sales Dataset:
   OrderID   Product  Quantity  UnitPrice  OrderDate Region  TotalPrice
0      101    Laptop         2    1211.42 2023-01-01   East     2422.84
1      102     Mouse         3    1222.13 2023-01-02   East     3666.39
2      103  Keyboard         1     957.52 2023-01-03  South      957.52
3      104   Monitor         3     222.03 2023-01-04   East      666.09
4      105    Webcam         1     547.55 2023-01-05   West      547.55

In [ ]:
data

{'OrderID': array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110]),
 'Product': ['Laptop',
  'Mouse',
  'Keyboard',
  'Monitor',
  'Webcam',
  'Headphones',
  'Speaker',
  'Router',
  'Printer',
  'SSD'],
 'Quantity': array([2, 3, 1, 3, 1, 3, 3, 4, 1, 4]),
 'UnitPrice': array([1211.42, 1222.13,  957.52,  222.03,  547.55,  821.59,  621.  ,
        1220.56,  584.96,  353.72]),
 'OrderDate': DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
                '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
                '2023-01-09', '2023-01-10'],
               dtype='datetime64[ns]', freq='D'),
 'Region': array(['East', 'East', 'South', 'East', 'West', 'East', 'North', 'North',
        'East', 'East'], dtype='<U5')}

In [ ]:
df = pd.DataFrame(data)
df

   OrderID     Product  Quantity  UnitPrice  OrderDate Region
0      101      Laptop         2    1211.42 2023-01-01   East
1      102       Mouse         3    1222.13 2023-01-02   East
2      103    Keyboard         1     957.52 2023-01-03  South
3      104     Monitor         3     222.03 2023-01-04   East
4      105      Webcam         1     547.55 2023-01-05   West
5      106  Headphones         3     821.59 2023-01-06   East
6      107     Speaker         3     621.00 2023-01-07  North
7      108      Router         4    1220.56 2023-01-08  North
8      109     Printer         1     584.96 2023-01-09   East
9      110         SSD         4     353.72 2023-01-10   East

In [ ]:
#2. Handling Missing Values, Duplicates, and Data Types
#Task 5: Load a DataFrame with missing values and fill them with appropriate values
#T#ask 6: Drop rows where any value is missing
#Ta#sk 8: Convert a column from string to numeric (handle errors gracefully)
#Task 9: Check and change data types of columns in a DataFrame

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print("library loaded")

library loaded

In [ ]:
data = {
    'ID': ['001', '002', '003', '004', '005', '002', np.nan],
    'Name': ['Alice', 'Bob', 'Charlie', None, 'Eve', 'Bob', 'Frank'],
    'Age': ['25', '30', '22', '28', np.nan, '30', '35'],
    'Salary': [50000, np.nan, 45000, 55000, 60000, 52000, 48000],
    'City': ['NYC', 'LA', 'NYC', 'Chicago', 'SF', 'LA', 'NYC']
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
display(df)

   OrderID     Product  Quantity  UnitPrice  OrderDate Region
0      101      Laptop         2    1211.42 2023-01-01   East
1      102       Mouse         3    1222.13 2023-01-02   East
2      103    Keyboard         1     957.52 2023-01-03  South
3      104     Monitor         3     222.03 2023-01-04   East
4      105      Webcam         1     547.55 2023-01-05   West
5      106  Headphones         3     821.59 2023-01-06   East
6      107     Speaker         3     621.00 2023-01-07  North
7      108      Router         4    1220.56 2023-01-08  North
8      109     Printer         1     584.96 2023-01-09   East
9      110         SSD         4     353.72 2023-01-10   East

In [ ]:
# fill missing values with
data_1 = {
    'ID': ['001', '002', '003', '004', '005', '002', np.nan],
    'Name': ['Alice', 'Bob', 'Charlie', None, 'Eve', 'Bob', 'Frank'],
    'Age': ['25', '30', '22', '28', np.nan, '30', '35'],
    'Salary': [50000, np.nan, 45000, 55000, 60000, 52000, 48000],
    'City': ['NYC', 'LA', 'NYC', 'Chicago', 'SF', 'LA', 'NYC']
}
data_1

{'ID': ['001', '002', '003', '004', '005', '002', nan],
 'Name': ['Alice', 'Bob', 'Charlie', None, 'Eve', 'Bob', 'Frank'],
 'Age': ['25', '30', '22', '28', nan, '30', '35'],
 'Salary': [50000, nan, 45000, 55000, 60000, 52000, 48000],
 'City': ['NYC', 'LA', 'NYC', 'Chicago', 'SF', 'LA', 'NYC']}

In [ ]:
data_1= pd.DataFrame(data_1)
data_1

    ID     Name  Age   Salary     City
0  001    Alice   25  50000.0      NYC
1  002      Bob   30      NaN       LA
2  003  Charlie   22  45000.0      NYC
3  004     None   28  55000.0  Chicago
4  005      Eve  NaN  60000.0       SF
5  002      Bob   30  52000.0       LA
6  NaN    Frank   35  48000.0      NYC

In [ ]:
data_1c= data_1.copy()

In [ ]:
data_1c

    ID     Name  Age   Salary     City
0  001    Alice   25  50000.0      NYC
1  002      Bob   30      NaN       LA
2  003  Charlie   22  45000.0      NYC
3  004     None   28  55000.0  Chicago
4  005      Eve  NaN  60000.0       SF
5  002      Bob   30  52000.0       LA
6  NaN    Frank   35  48000.0      NYC

In [ ]:
data_1c['Salary'].fillna(data_1c['Salary'].mean())

0    50000.000000
1    51666.666667
2    45000.000000
3    55000.000000
4    60000.000000
5    52000.000000
6    48000.000000
Name: Salary, dtype: float64

In [ ]:
data_1c['Name'].fillna('unknown')

0      Alice
1        Bob
2    Charlie
3    unknown
4        Eve
5        Bob
6      Frank
Name: Name, dtype: object

In [ ]:
data_1c['ID'].fillna('missing')

0        001
1        002
2        003
3        004
4        005
5        002
6    missing
Name: ID, dtype: object

In [ ]:
data_1c.dropna()

    ID     Name Age   Salary City
0  001    Alice  25  50000.0  NYC
2  003  Charlie  22  45000.0  NYC
5  002      Bob  30  52000.0   LA

In [ ]:
# identify and remove duplicates
duplicates = data_1c.duplicated()
print(duplicates)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [ ]:
data_1c.drop_duplicates()

    ID     Name  Age   Salary     City
0  001    Alice   25  50000.0      NYC
1  002      Bob   30      NaN       LA
2  003  Charlie   22  45000.0      NYC
3  004     None   28  55000.0  Chicago
4  005      Eve  NaN  60000.0       SF
5  002      Bob   30  52000.0       LA
6  NaN    Frank   35  48000.0      NYC

In [ ]:
pd.to_numeric(data_1c['Age'], errors = 'coerce')

0    25.0
1    30.0
2    22.0
3    28.0
4     NaN
5    30.0
6    35.0
Name: Age, dtype: float64

In [ ]:
# shaow og datatype
print(data_1.dtypes)

ID         object
Name       object
Age        object
Salary    float64
City       object
dtype: object

In [ ]:
data_1.astype('string')

     ID     Name   Age   Salary     City
0   001    Alice    25  50000.0      NYC
1   002      Bob    30     <NA>       LA
2   003  Charlie    22  45000.0      NYC
3   004     <NA>    28  55000.0  Chicago
4   005      Eve  <NA>  60000.0       SF
5   002      Bob    30  52000.0       LA
6  <NA>    Frank    35  48000.0      NYC